# Generated by Django 3.2.7 on 2025-11-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
