# Generated by Django 3.2.7 on 2025-11-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
