# Generated by Django 3.2.7 on 2025-11-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0008_productorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
