# Generated by Django 3.2.7 on 2025-11-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0010_cartitem2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem2',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbs.product2'),
        ),
    ]
