# Generated by Django 3.2.7 on 2025-11-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0012_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
